### ISSUE TITLE
Feature tracker

### ISSUE THREAD

**Issue by kbarbary** [JuliaAstro/FITSIO.jl#37]
This is an issue to track some obvious features that should be added. My guess is that they will be added gradually over time as needed, but in a backwards-compatible manner.

**General**

- [ ] Iterator protocol for `FITS` type: enabling `for hdu in FITS(...)`
- [ ] Improve appearance of `show()` for FITS and HDU types.

**Images**

- [ ] Write to a subset of the image: `write(hdu, data; start=(100, 200))`
- [ ] Read to already-allocated array: `read!(hdu, data)`, `read!(hdu, 1:20, 1:30, data)` 
- [ ] Read/write tile-compressed images.

**Tables**

- [x] Read and write variable length table columns [#36]
- [ ] Read ranges of table rows: `read(hdu, "COLNAME", 1:10)`
- [ ] Read arbitrary table rows: `read(hdu, "COLNAME", [1, 3, 6, 10])`
- [ ] Append rows to a table
- [ ] Insert columns into a table
- [ ] Read/write bit columns (into `BitArray`s?)
- [ ] Iterate over table rows?
- [ ] Read multiple columns simultaneously (requires low-level tinkering, byteswapping)

**Comment by mileslucas** [comment]
Possible feature (I'm not sure if functionality exists in `cfitsio`)
`write!(hdu, data)`
`write!(fits, i, data)`
to overwrite the data in a given HDU. Currently the only option is to append a new HDU.

**Comment by jishnub** [comment]
Currently we check the strides of the array to determine if the memory layout is contiguous. This is too conservative, but I don't know of a workaround right now other than using a `Union` of compatible types. For example, this means that currently writing out something like a `Transpose` is not supported even if the memory layout of its parent is contiguous. 

Keeping [`julia#10889`](https://github.com/JuliaLang/julia/issues/10889) in mind, we may eventually use a trait-based check for contiguity instead of a strides-based approach as in the case now.
